version: '3.8'

services:  
  database:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: supermercado_antojitos
    container_name: riskpruebatecnica_database
    volumes:
      - ./postgres:/var/lib/postgresql/data
